<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$conn = mysqli_connect('localhost','root','root','ranchhand');
//$db = mysql_select_db('hery',$conn);

$query = 'select * from `dealer_information_new`';
$result = mysqli_query($conn, $query);
?>
<table style="border:solid 1px;">
    <tr><th>Requested Url</th><th>Targeted Url</th></tr>
<?php
//mysqli_fetch_array($result)
while($row = mysqli_fetch_array($result)){
    if($row['listing_title_alias']==""){
        $alias = str_replace(' ','-',$row['listing_title']);
        $alias = str_replace('&','',$alias);
    }else{
        $alias = $row['listing_title_alias'];
    }
//    echo '<tr><td style="border:solid 1px;">dealers/index/display/id/'.$row['id'].'</td><td style="border:solid 1px;">dealers/'.$row['listing_title_alias'].'</td></tr>';
    
    echo 'INSERT INTO url_rewrite (entity_type,entity_id,request_path,target_path,redirect_type,store_id,description,is_autogenerated,metadata) VALUES ("custom",0,"dealers/'.strtolower($alias).'","dealers/index/display/id/'.$row['id'].'",0,1,NULL,0,NULL);';
    echo '</br>';
}
?>    
</table>
