<?php

namespace Ranchhand\Dealers\Controller\Adminhtml\Dealer;

use Ranchhand\Dealers\Controller\Adminhtml\Dealer;
use \Magento\Framework\Image\AdapterFactory;
use \Magento\Backend\App\Action\Context;
use \Magento\Framework\Registry;
use \Magento\Framework\View\Result\PageFactory;
use Ranchhand\Dealers\Model\DealerFactory;

class Save extends Dealer
{

    protected $adapterFactory;


    public function __construct(Context $context, Registry $coreRegistry, PageFactory $resultPageFactory, DealerFactory $dealerFactory, AdapterFactory $adapterFactory)
    {
        $this->adapterFactory = $adapterFactory;
        parent::__construct($context, $coreRegistry, $dealerFactory, $resultPageFactory);
  
    }


    /**
     * @return void
     */
    public function execute()
    {
         $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
         $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
         $connectionDb = $resource->getConnection();
            
            
        $formData = $this->getRequest()->getParam('dealer');
        $formData['jr_image']='';
        $isPost = $this->getRequest()->getPost();
        $urlAlies= $isPost['dealer']['listing_title_alias'];
        $isDealerId='';
          if(isset($isPost['dealer']['id'])){
         $isDealerId= $isPost['dealer']['id'];
          }
        $dealerId = $this->getRequest()->getParam('id');  
         //check is there image with the dealer data
        if($_FILES["jr_image"]["name"]==''){
            if(array_key_exists('id', $formData)){
              $imgData= $this->checkImage($formData['id']);
            if($imgData[0]['jr_image'] !=''){
            //    if(){}
                 if(array_key_exists('delete',$isPost['dealer']['jr_image'])){
            // "delete image";
                     $formData['jr_image']='';
        }else{
                $formData['jr_image']=$imgData[0]['jr_image'];
        }
            }
            }
          //  echo "no file uploaded";
        }else{
            $formData['jr_image']=$_FILES["jr_image"]["name"];
                  $this->fileUpload($_FILES);
                 // echo "file uploaded";
            }

        if(!isset($formData['use_delaer_description'])){
            $formData['use_delaer_description']=0;
        }else{
            $formData['use_delaer_description']=1;
        }  
               

        if ($isPost) {
            $dealerModel = $this->_dealerFactory->create();
            $dealerId = $this->getRequest()->getParam('id');
            if ($dealerId) {
               
                $dealerModel->load($dealerId);
            }
             //code check existing ur rewrite
            if($isDealerId){
                   $query =  "Select * from url_rewrite where target_path= 'dealers/index/display/id/$isDealerId' or request_path='dealers/$urlAlies' ";
              //  echo $query;
                //fetchAll
               $dataRes = $connectionDb->fetchAll($query);
               if($dataRes){
                   //update data;
                  $urlId= $dataRes[0]['url_rewrite_id'];
                    $query="update url_rewrite set  target_path= 'dealers/index/display/id/$isDealerId' , request_path='dealers/$urlAlies' where  url_rewrite_id='$urlId'";
                    $connectionDb->exec($query);
               }else{
                      $query =  "insert into url_rewrite (entity_type,entity_id,request_path,target_path,redirect_type,store_id,description,is_autogenerated,metadata) values('custom','0','dealers/$urlAlies','dealers/index/display/id/$lastInsertedDealerId','0','1','','0','')";
                // $query = "";
                    $collection = $connectionDb->exec($query);
               }
            }

            $dealerModel->setData($formData);
           
            try {
                // Save news
                $dealerModel->save();
                if(!$isDealerId){
                $lastInsertedDealerId = $dealerModel->getId();
                //add url rewrite to the table
              $query =  "insert into url_rewrite (entity_type,entity_id,request_path,target_path,redirect_type,store_id,description,is_autogenerated,metadata) values('custom','0','dealers/$urlAlies','dealers/index/display/id/$lastInsertedDealerId','0','1','','0','')";
                // $query = "";
                    $collection = $connectionDb->exec($query);
                }
                // Display success message
                $this->messageManager->addSuccess(__('The dealer has been saved.'));

                // Check if 'Save and Continue'
                if ($this->getRequest()->getParam('back')) {
                    $this->_redirect('*/*/edit', ['id' => $dealerModel->getId(), '_current' => true]);
                    return;
                }

                // Go to grid page
                $this->_redirect('*/*/');
                return;
            } catch (\Exception $e) {
                $this->messageManager->addError($e->getMessage());
            }

            $this->_getSession()->setFormData($formData);
            $this->_redirect('*/*/edit', ['id' => $dealerId]);
        }
    }
    public function fileUpload($file){
//echo $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
          //contents folders
        $target_dir = BP."/images/dealer-images/";
        $target_file = $target_dir . basename($file["jr_image"]["name"]);
        //static conent folders
          $target_dir1 =BP."/pub/media/";
        $target_file1 = $target_dir1 . basename($file["jr_image"]["name"]);
        
      //  echo $target_file;
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
//        // Check if image file is a actual image or fake image
//        if(isset($_POST["submit"])) {
        $check = getimagesize($file["jr_image"]["tmp_name"]);
        if($check !== false) {
       // echo "File is an image - " . $check["mime"] . ".";
        $uploadOk = 1;
        } else {
       // echo "File is not an image.";
        $uploadOk = 0;
        }
 //       }
//        // Check if file already exists
//        if (file_exists($target_file)) {
//        echo "Sorry, file already exists.";
//        $uploadOk = 0;
//        }
//        // Check file size
//        if ($_FILES["fileToUpload"]["size"] > 500000) {
//        echo "Sorry, your file is too large.";
//        $uploadOk = 0;
//        }
//        // Allow certain file formats
//        if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
//        && $imageFileType != "gif" ) {
//        echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed.";
//        $uploadOk = 0;
//        }
        // Check if $uploadOk is set to 0 by an error
        if ($uploadOk == 0) {
        echo "Sorry, your file was not uploaded.";
        // if everything is ok, try to upload file
        } else {
        if (move_uploaded_file($file["jr_image"]["tmp_name"], $target_file)) {
               chmod($target_file, 0755);
               copy($target_file,$target_file1);
               
        //echo "The file ". basename( $file["jr_image"]["name"]). " has been uploaded.";
        } else {
        echo "Sorry, there was an error uploading your file.";
        }
        
}

   
}
function checkImage($dealerId){
     $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connectionDb = $resource->getConnection();
            $tableName = $resource->getTableName('dealer_information');
            $checkDealer="SELECT * FROM $tableName WHERE id = $dealerId";
            $resultDealer =$connectionDb->fetchAll($checkDealer);
            return $resultDealer;
}
}