<?php 
$contactDetails  = '<div style="width:100%"><img  src="http://kasparcompanies.com/images/Kaspar-Logo-Cyan.png"> </div>';
$contactDetails .= '<h3 align="left" style="text-transform:uppercase">Job Application Request ' . $contact_info['first_name'] . ' ' . $contact_info['last_name'].'</h3>';
$contactDetails .= '<table cellspacing="0" cellpadding="5" border="0">';
$contactDetails .= '<tr><th colspan="4" style="color:#00ADEF;text-transform:uppercase"><h3>Personal Contact information</h3></th></tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td>' . $contact_info['first_name'] . '</td>';
$contactDetails .= '<td>' . $contact_info['last_name'] . '</td>';
$contactDetails .= '<td>' . $contact_info['mi'] . '</td>';
$contactDetails .= '<td>'. $contact_info['application_date'] . '</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td style="border-top:1px solid #ccc">First name</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Last name</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">M.I</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Application Date</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td>' . $contact_info['address'] . '</td>';
$contactDetails .= '<td>' . $contact_info['city'] . '</td>';
$contactDetails .= '<td>' . $contact_info['state'] . '</td>';
$contactDetails .= '<td>' . $contact_info['zipcode'] . '</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Address</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">City</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">State</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Zip code</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td>' . $contact_info['primary_phone_number'] . '</td>';
$contactDetails .= '<td>' . $contact_info['secondary_phone_number'] . '</td>';
$contactDetails .= '<td>' . $contact_info['email'] . '</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Primary phone number</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Secondary phone number</td>';
$contactDetails .= '<td style="border-top:1px solid #ccc">Email address</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td colspan="4" >Are you 18 or older?</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td colspan="4">' . $contact_info['over_18'] . '</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td colspan="4">Are you either a US citizen or an Allen authorized to work in the United States</td>';
$contactDetails .= '</tr>';
$contactDetails .= '<tr>';
$contactDetails .= '<td colspan="4">' . $contact_info['us_citizen'] . '</td>';
$contactDetails .= '</tr>';